name: Docker Image Pull and Tar Creation

on: [ workflow_dispatch ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Pull Docker images
        run: |
          docker pull coredgeio/kube-controller-manager
        
      - name: Create tarball
        run: |
          docker save coredgeio/kube-controller-manager | gzip > docker_images.tar.gz

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: docker_images
          path: docker_images.tar.gz
