name: Docker Image Pull and Tar Creation
env:
  K8s-VERSION: "v1.27.6"
  Cloud_orbiter: "2024-02-05"

on: [ workflow_dispatch ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Login to Docker
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Pull Docker images of k8s-core-components
        run: |
          docker pull coredgeio/kube-controller-manager:${{ env.K8s-VERSION }}
          docker pull coredgeio/kube-scheduler:${{ env.K8s-VERSION }}
          docker pull coredgeio/kube-proxy:${{ env.K8s-VERSION }}
          docker pull coredgeio/kube-apiserver:${{ env.K8s-VERSION }}
      - name: Pull Docker images of k8s-core-components 
        run: |
          images=(
            "compass-api"
            "compass-cloud-manager"
            "compass-cluster-manager"
            "compass-controller"
            "compass-metric-server"
            "compass-orchestrator"
            "compass-term"
            "frontend"
            "kg-cluster-notifier"
            "kgapp"
          )
      
          for image in "${images[@]}"; do
            docker pull "coredgeio/$image:${{ env.Cloud_orbiter }}"
            docker pull "kg-keycloak:19.0.3-7"
            docker pull "minio:RELEASE.2019-12-17T23-16-33Z"
            docker pull "mongo:5.0.3"
            docker pull "workflow-controller"
            docker pull "workflowcli:14092021"
            docker pull "mysql:8.0"
            docker pull "postgres:9.5"
            docker pull "redis:6.2.5"
            docker pull "argoexec:latest"
          done
      
      - name: Create tarball
        run: |
          docker save $(docker images --format "{{.Repository}}:{{.Tag}}" "coredgeio/*") | gzip > docker_images_${{ env.K8s-VERSION }}.tar.gz


    
        
      # - name: Create tarball
      #   run: |
      #     docker save coredgeio/kube-controller-manager:${{ env.K8s-VERSION }} coredgeio/kube-proxy:${{ env.K8s-VERSION }} coredgeio/kube-scheduler:${{ env.K8s-VERSION }} coredgeio/kube-apiserver:${{ env.K8s-VERSION }} | gzip > docker_images_${{ env.K8s-VERSION }}.tar.gz

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: docker_images
          path: docker_images_${{ env.Cloud_orbiter }}.tar.gz
